name: tars
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - pytorch
dependencies:
  - python=3.11
  - pip
  - pip:
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-ml-py==12.570.86
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.1.105
      - torch==2.4.0
      - accelerate==1.4.0
      - antlr4-python3-runtime==4.9.3
      - datasets==3.3.2
      - huggingface-hub==0.29.1
      - numpy==1.26.4
      - openai==1.63.2
      - ray==2.40.0
      - sentence-transformers==3.4.1
      - sentencepiece==0.2.0
      - tenacity==9.0.0
      - tqdm==4.67.1
      - transformers==4.49.0
      - vllm==0.5.4
      - vllm-flash-attn==2.6.1
      - wandb==0.21.0
